<?php

<<<<<<<< HEAD:var/cache/dev/ContainerEVLu7xd/getResponseService.php
namespace ContainerEVLu7xd;
========
namespace ContainerTksq2bE;
>>>>>>>> d37af2c76241d2721ee751a5b98ea271824e379d:var/cache/dev/ContainerTksq2bE/getResponseService.php


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getResponseService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.beq5mCo.Symfony\Component\HttpFoundation\Response' shared service.
     *
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.beq5mCo": it references class "Symfony\\Component\\HttpFoundation\\Response" but no such service exists.');
    }
}
