<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< HEAD
if (\class_exists(\ContainerEVLu7xd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEVLu7xd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEVLu7xd.legacy');
=======
if (\class_exists(\ContainerTksq2bE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTksq2bE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTksq2bE.legacy');
>>>>>>> d37af2c76241d2721ee751a5b98ea271824e379d

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
<<<<<<< HEAD
    \class_alias(\ContainerEVLu7xd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEVLu7xd\App_KernelDevDebugContainer([
    'container.build_hash' => 'EVLu7xd',
    'container.build_id' => 'd6d2e8b9',
    'container.build_time' => 1649334032,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEVLu7xd');
=======
    \class_alias(\ContainerTksq2bE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTksq2bE\App_KernelDevDebugContainer([
    'container.build_hash' => 'Tksq2bE',
    'container.build_id' => 'c2db1afd',
    'container.build_time' => 1649333010,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTksq2bE');
>>>>>>> d37af2c76241d2721ee751a5b98ea271824e379d
