<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTksq2bE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTksq2bE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTksq2bE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTksq2bE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTksq2bE\App_KernelDevDebugContainer([
    'container.build_hash' => 'Tksq2bE',
    'container.build_id' => 'c2db1afd',
    'container.build_time' => 1649333010,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTksq2bE');
